### ISSUE TITLE
Missing return statement

### ISSUE THREAD

**Issue by c-plowman** [pritchardn/qolab#10]
```c
void* initialise_state(MKL_Complex16 *state, machine_spec_t *mach_spec) 
```
In state_evolve.c this generic pointer function has no return statement. Compiler aborts because of this. 

![icc_error](https://user-images.githubusercontent.com/46660727/51095823-64ab8e80-17f2-11e9-8e90-4c8571bebb60.PNG)

**Comment by pritchardn** [comment]
Function declaration has been changed to `void`
