### ISSUE TITLE
Makefile linking missing files?

### ISSUE THREAD

**Issue by c-plowman** [pritchardn/qolab#11]
Makefile doesn't seem to be linking state_evolve.c (and header), or reporting.c (and header), or spmatrix_expm.c (and header). 
This causes various reference errors in qaoa.c when compiling.

![makefile](https://user-images.githubusercontent.com/46660727/51095943-645fc300-17f3-11e9-901b-d7e76f678ee0.PNG)

Adding to SRCS,
```c
$(LOC)/state_evolve.c $(LOC)/reporting.c
```
and to HEADERS,
```c
$(LOC)/state_evolve.h $(LOC)/reporting.h
```
seems to fix the issue. Perhaps permanently add these to the Makefile?

Edit: spmatrix_expm missing too.

**Comment by pritchardn** [comment]
Adjusted makefile has been dropped into master. 
(Cmake has been the default build tool for a little while, makefile support was a little behind)
