### ISSUE TITLE
Probability greater than 1 occasionally

### ISSUE THREAD

**Issue by c-plowman** [pritchardn/qolab#29]
Sometimes the probability is larger than 1, which seems odd.
![probability](https://user-images.githubusercontent.com/46660727/52317930-2a05d200-29fd-11e9-9d47-dcd5240a2186.PNG)

**Comment by myxie** [comment]
Mind if I have a look at what's causing this @pritchardn?

**Comment by pritchardn** [comment]
If you can find the time feel free

**Comment by pritchardn** [comment]
I think I know what's happening, it's do to with the matrix exponential. It relies on an estimate of the eigenvalues of the UB matrix. I have been setting this as +- num_qubits. This is typically fine for the standard QAOA (but has been problematic for some reasone)

This is problematic for the restricted QAOA where elements are removed thus making the eigenvalue estimate poor

We will need to implement eigenvalue solving for the maximal value

**Comment by pritchardn** [comment]
Fixed with the mother of all updates
  - The problem was with eigenvalue estimates - so I solve for the maximal one now
  - The caveat is that internally this calls Intel's FFT code which only supports 32bit builds
tl:dr - we have to go to 32bit precision capping scale at 31 qubits :(
